tables:
  # Batch data
  customers:
    file_type: "csv"
    required_columns: 
      - "customer_id"
      - "full_name"
      - "email"
      - "phone"
      - "region_id"
      - "segment_name"
      - "discount_pct"
      - "signup_date"
      - "gender"
    types:
      customer_id: "int"
      full_name: "string"
      email: "string"
      phone: "string"
      region_id: "int"
      segment_name: "string"
      discount_pct: "float"
      signup_date: "date"
      gender: "string"
    primary_key: "customer_id"

  drivers:
    file_type: "csv"
    required_columns:
      - "driver_id"
      - "driver_name"
      - "driver_phone"
      - "national_id"
      - "region_id"
      - "shift"
      - "vehicle_type"
      - "hire_date"
      - "rating_avg"
      - "is_active"
    types:
      driver_id: "int"
      driver_name: "string"
      driver_phone: "string"
      national_id: "string"
      region_id: "int"
      shift: "string"
      vehicle_type: "string"
      hire_date: "date"
      rating_avg: "float"
      is_active: "boolean"
    primary_key: "driver_id"

  restaurants:
    file_type: "json"
    required_columns:
      - "restaurant_id"
      - "restaurant_name"
      - "region_id"
      - "category_id"
      - "price_tier"
      - "rating_avg"
      - "is_active"
    types:
      restaurant_id: "int"
      restaurant_name: "string"
      region_id: "int"
      category_id: "int"
      price_tier: "int"
      rating_avg: "float"
      is_active: "boolean"
    primary_key: "restaurant_id"

  agents:
    file_type: "csv"
    required_columns:
      - "agent_id"
      - "agent_name"
      - "agent_email"
      - "team_name"
      - "hire_date"
      - "is_active"
    types:
      agent_id: "int"
      agent_name: "string"
      agent_email: "string"
      team_name: "string"
      hire_date: "date"
      is_active: "boolean"
    primary_key: "agent_id"


  teams:
    file_type: "csv"
    required_columns:
      - "team_id"
      - "team_name"
    types:
      team_id: "int"
      team_name: "string"
    primary_key: "team_id"

  channels:
    file_type: "csv"
    required_columns:
      - "channel_id"
      - "channel_name"
    types:
      channel_id: "int"
      channel_name: "string"
    primary_key: "channel_id"

  priorities:
    file_type: "csv"
    required_columns:
      - "priority_id"
      - "priority_code"
      - "priority_name"
      - "sla_first_response_min"
      - "sla_resolution_min"
    types:
      priority_id: "int"
      priority_code: "string"
      priority_name: "string"
      sla_first_response_min: "int"
      sla_resolution_min: "int"
    primary_key: "priority_id"

  reason_categories:
    file_type: "csv"
    required_columns:
      - "reason_category_id"
      - "category_name"
    types:
      reason_category_id: "int"
      category_name: "string"
    primary_key: "reason_category_id"

  cities:
    file_type: "json"
    required_columns:
      - "city_id"
      - "city_name"
      - "country"
      - "timezone"
    types:
      city_id: "int"
      city_name: "string"
      country: "string"
      timezone: "string"
    primary_key: "city_id"
  # Stream data
  orders:
    file_type: "json"
    required_columns:
      - "order_id"
      - "customer_id"
      - "restaurant_id"
      - "driver_id"
      - "region_id"
      - "order_amount"
      - "total_amount"
      - "order_status"
      - "order_created_at"
    types:
      order_id: "int"
      customer_id: "int"
      restaurant_id: "int"
      driver_id: "int"
      region_id: "int"
      order_amount: "float"
      total_amount: "float"
      order_status: "string"
      order_created_at: "timestamp"
    primary_key: "order_id"

  tickets:
    file_type: "csv"
    required_columns:
      - "ticket_id"
      - "order_id"
      - "customer_id"
      - "agent_id"
      - "reason_id"
      - "priority_id"
      - "status"
      - "created_at"
    types:
      ticket_id: "int"
      order_id: "int"
      customer_id: "int"
      agent_id: "int"
      reason_id: "int"
      priority_id: "int"
      status: "string"
      created_at: "timestamp"
    primary_key: "ticket_id"

  ticket_events:
    file_type: "json"
    required_columns:
      - "event_id"
      - "ticket_id"
      - "agent_id"
      - "new_status"
      - "event_ts"
    types:
      event_id: "int"
      ticket_id: "int"
      agent_id: "int"
      new_status: "string"
      event_ts: "timestamp"
    primary_key: "event_id"
